### ISSUE TITLE
origin of class embeddings

### ISSUE THREAD

**Issue by yaohusama** [IDEA-Research/MP-Former#1]
I would like to ask, how to obtain class embeddings, but it does not seem to be mentioned in the paper.

**Comment by HaoZhang534** [comment]
> I would like to ask, how to obtain class embeddings, but it does not seem to be mentioned in the paper.

Class embeddings are learnable embeddings with shape (num_classes, num_dimensions) where each class has a unique embedding.

**Comment by yaohusama** [comment]
> I know that the class embedding in the matching part is a learnable parameter, but is the GT class embedding added in the 

> training phase also learnable?  

I just found out that it should be the same as dn-detr, which is to determine a learnable embedding matrix and look up the table from the matrix according to the category. Thank you for your guidance.

**Comment by HaoZhang534** [comment]
@yaohusama  Yes, your understanding is right.

**Comment by skyABB** [comment]
我希望这条消息能找到你，我对你为类开发的代码特别感兴趣——嵌入。我相信这段代码对我自己的项目非常有价值，并想询问您是否愿意考虑开源它。

**Comment by skyABB** [comment]
我希望这条消息能找到你，我对你为类开发的代码特别感兴趣——嵌入。我相信这段代码对我自己的项目非常有价值，并想询问您是否愿意考虑开源它。
