### ISSUE TITLE
when to publish code

### ISSUE THREAD

**Issue by Manningchan** [IDEA-Research/MP-Former#2]

**Comment by zhangkui669** [comment]
soon

**Comment by a5336033** [comment]
Thank you and hope the code can publish soon.

**Comment by HarisIqbal89** [comment]
代码开源了吗？如开

**Comment by sorrowyn** [comment]
Hello Zhanghao, we are looking forward to you releasing the code.
✊ :
@HaoZhang534

**Comment by hzd493** [comment]
Hello author, could you send a copy of the source code to my email?Thanks.

**Comment by HaoZhang534** [comment]
@sorrowyn @zhangkui669 @Manningchan @hzd493 @a5336033 Thank you for your interest. The code is released.
