### ISSUE TITLE
How to learn your code?

### ISSUE THREAD

**Issue by Levine66** [IDEA-Research/MP-Former#4]
Hey, thanks for your brilliant work. I just learned in MaskFormer and Mask2Former recently, and i want to know the difference between your work and Mask2Former. I found that the structure of this repository  is very similar to the official code of Mask2Former, which makes me hard to know the exactly changes you made. Besides, I just found there are a lot of new functions in mask2former_transformer_decoder.py.  

So would you please give me some advices to quickly learn your code?

**Comment by HaoZhang534** [comment]
@Levine66  The only differences are in mask2former_transformer_decoder.py and criterion.py. The new functions are different versions of constructing MP training queries.

**Comment by Levine66** [comment]
Thanks for your reply. I figured it out by reading your code!

**Comment by HarisIqbal89** [comment]
> @Levine66 The only differences are in mask2former_transformer_decoder.py and criterion.py. The new functions are different versions of constructing MP training queries.

hello author, may I ask a question about mask2former_transformer_decoder.py. In line 719~728，the code get some parameters from config. Such as dn_mode and head_dn，But I could not find them among the config.  So, I want to know whether it matter to the result？Actually, I want to change my code which based mask2former to MP-former. I simply change the mask2former_transformer_decoder.py and criterion.py. Do I need to change any other code, I am looking forward to receive reply from you  :)
