### ISSUE TITLE
About mask2former_transformer_decoder.py

### ISSUE THREAD

**Issue by HarisIqbal89** [IDEA-Research/MP-Former#7]
hello author, may I ask a question about mask2former_transformer_decoder.py. In line 719~728，the code get some parameters from config. Such as dn_mode and head_dn，But I could not find them among the config.  So, I want to know whether it matter to the result？Actually, I want to change my code which based mask2former to MP-former. I simply change the mask2former_transformer_decoder.py and criterion.py. Do I need to change any other code, I am looking forward to receive reply from you  :)
        ret["mask_dim"] = cfg.MODEL.SEM_SEG_HEAD.MASK_DIM
        ret["dn_mode"] = cfg.MODEL.MASK_FORMER.DN_MODE
        ret["head_dn"] = cfg.MODEL.MASK_FORMER.HEAD_DN
        ret["all_lys"] = cfg.MODEL.MASK_FORMER.ALL_LY_DN
        ret["dn_ratio"] = cfg.MODEL.MASK_FORMER.DN_RATIO
        ret["dn_label_noise_ratio"] = cfg.MODEL.MASK_FORMER.LB_NOISE_RATIO

**Comment by HaoZhang534** [comment]
Some parameters are defined in [link](https://github.com/IDEA-Research/MP-Former/blob/a71f504a467d7079cf02726a05ff23bbb933607d/mask2former/config.py#L65C16-L65C16) , you can overwrite them in config file or in command line. If you do not overwrite them, they will use the default value in https://github.com/IDEA-Research/MP-Former/blob/a71f504a467d7079cf02726a05ff23bbb933607d/mask2former/config.py

**Comment by HarisIqbal89** [comment]
> Some parameters are defined in [link](https://github.com/IDEA-Research/MP-Former/blob/a71f504a467d7079cf02726a05ff23bbb933607d/mask2former/config.py#L65C16-L65C16) , you can overwrite them in config file or in command line. If you do not overwrite them, they will use the default value in https://github.com/IDEA-Research/MP-Former/blob/a71f504a467d7079cf02726a05ff23bbb933607d/mask2former/config.py

thank you for your reply.So I just need to change three codes to modify mask2former to MPformer: mask2former_transformer_decoder.py and criterion.py and config.py，right？MP-former is wonderful！
